config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks
  devise_for :users
  root "welcome#index"
  get "my_portfolio", to: 'users#my_portfolio'
  get "/search_stock", to: 'stocks#search'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stock.rb
class Stock < ApplicationRecord
  include HTTParty

  has_many :user_stocks
  has_many :users, through: :user_stocks
  validates :name, presence: true
  validates :ticker, presence: true


  base_uri 'https://rest.coinapi.io'
  def self.new_lookup(ticker_symbol)
    headers = {
      'X-CoinAPI-Key' => '2198FA7A-F6EF-4A0D-9738-4FE9D396FEAF'
    }

    # Fetch the stock price
    response = get("/v1/exchangerate/#{ticker_symbol}/USD", headers: headers)

    if response.success?
      last_price = response.parsed_response['rate']
    else
      Rails.logger.error("Failed to fetch price for #{ticker_symbol}: #{response.body}")
      last_price = nil
    end
    # Create and return a new Stock instance
    new(
      ticker: ticker_symbol,
      name: ticker_symbol.upcase,
      last_price: last_price
    )
  rescue StandardError => e
    Rails.logger.error("Error fetching stock details: #{e.message}")
    nil
  end
end

app/models/user.rb
class User < ApplicationRecord

 has_many :user_stocks
 has_many :stocks, through: :user_stocks

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
# class StocksController < ApplicationController
#   def search
#     if params[:stock].present?
#       @stock = Stock.new_lookup(params[:stock])

#       respond_to do |format|
#         if @stock
#           
#           format.js   { render partial: 'users/search' , status: :ok}
#         else
#           flash[:alert] = "Invalid Search - Stock not found."
#           format.html { redirect_to my_portfolio_path, alert: flash[:alert] }
#           format.js   { render js: "alert('#{flash[:alert]}');" }
#         end
#       end
#     else
#       flash[:alert] = "The search cannot be empty."
#       respond_to do |format|
#         format.html { redirect_to my_portfolio_path, alert: flash[:alert] }
#         format.js   { render js: "alert('#{flash[:alert]}');" }
#       end
#     end
#   end
# end

class StocksController <ApplicationController
    
  def search
      if params[:stock].present?            
           @stock = Stock.new_lookup(params[:stock])
           if @stock            
              respond_to do |format|
                format.html { render 'users/my_portfolio', status: :ok }
                  format.js { render partial: 'users/search' }
              end         
           else
              flash[:alert] = "Please enter a valid symbol to search"
              redirect_to my_portfolio_path
           end             
      else 
          flash[:alert] = "Please enter a symbol to search"
          redirect_to my_portfolio_path
      end
  end
  
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
      @tracked_stocks = current_user.stocks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/views/layouts/_messages.html.erb
    <% if notice  %>
        <div class="alert alert-success notice" role="alert">
            <%= notice %>
        </div>
    <%end %>
    <% if alert %>
        <div class="alert alert-danger alert" role="alert">
            <%= alert %>
        </div>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
      .search-area{
        padding:30px;
      } 
      .results-block {
          display: inline-block;
      } 
      .logout_button {
        margin: 5px;
      }
    </style>
  </head>
  <body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to "Finance Tracker" , root_path , class: "navbar-brand" %>
    <% if current_user %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= 'active' if request.path == my_portfolio_path%>">
          <%= link_to "My Portfolio", my_portfolio_path , class:"nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a href="#" class="btn btn-danger logout_button" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
          <%= form_with url: destroy_user_session_path, method: :delete, id: "logout-form", style: "display: none;" do %>
          <% end %>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
    <%end %>
  </div>
</nav>
  <div class="container">

    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
  
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </body>
</html>

app/views/stocks/_list.html.erb
<% if @tracked_stocks.present? %>
    <div class="row">
        <div class="col-9">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Ticker</th>
                        <th scope="col">Name</th>
                        <th scope="col">Price</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <% @tracked_stocks.each do |stock| %>
                        <tr>
                            <th scope="row"><%= stock.ticker %></th>
                            <td><%= stock.name %></td>
                            <td>$ <%= stock.last_price %></td>
                            <td></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
<% else %>
    <p>No stocks to display.</p>
<% end %>

app/views/users/_result.html.erb
    <div class="card card-header results-block">
        <strong>Symbol:</strong> <%= @stock.ticker %><br>
        <strong>Name:</strong> <%= @stock.name %><br>
        <strong>Price:</strong> $ <%= @stock.last_price %>
    </div>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class="search-area">
    <h3>Search Crypto Currency</h3>

        <%= form_tag search_stock_path, remote: true, method: :get, id: 'stock-search-form' do %>
        <div class="form-group row">
            <div class="col-sm-9">
            <%= text_field_tag :stock, params[:stock], placeholder: "Crypto ticker Symbol", autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class="col-sm-3">
            <%= button_tag type: :submit, class: "btn btn-success btn-lg" do %>
                <%= 'Search' %>
            <% end %>
            </div>
  </div>
<% end %>
</div>
  <div id="results">
  
  </div>

app/views/users/search.js.erb
document.querySelector('#results').innerHTML = `<%= render 'users/result.html' %>`;

app/views/welcome/index.html.erb
<h1>Welcome to the Financial Tracker App</h1>
<%= link_to "Sign out", destroy_user_session_path, data:{turbo_method: :delete} %>